In [0]:
import numpy as np
from sklearn import datasets
data=datasets.load_breast_cancer()

In [0]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [0]:
print(data['target_names'])
print(data['feature_names'])
len(data['feature_names'])
print(data['target_names'])

['malignant' 'benign']
['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
['malignant' 'benign']


#breast_cancer 

-data: 569개의 data가 30개의 label로 구성됨

mean(평균), standard_error(표준오류), worst(최악)

radius 반경                    
texture 질감             
perimeter 둘레                 
area 면적               
smoothness 부드러움                  
compactness 압축성                 
concavity 오목함                    
concave points  오목점              
symmetry 대칭                    
fractal dimension 프랙탈차원 


-feature_names : 30개

-target_names : malignant악성, benign양성 

-target : 0 ,1 로 판정

In [0]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [0]:
print(data['data'])

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [0]:
type(data['data']),data['data'].shape

(numpy.ndarray, (569, 30))

In [0]:
print(data['data'][0])      
a=data['data'] 

[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
 1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
 6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
 1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
 4.601e-01 1.189e-01]


In [0]:
#mean radius의 평균, 중간값, 표준편차, 분산
mean_rm=np.mean(a[:,0])
print(mean_rm)
medi_rm=np.median(a[:,0])
print(medi_rm)
std_rm=np.std(a[:,0])
print(std_rm)
var_rm=np.var(a[:,0])
print(var_rm)
min_rm=np.min(a[:,0])
print(min_rm)
max_rm=np.max(a[:,0])
print(max_rm)

14.127291739894552
13.37
3.520950760711062
12.397094259351807
6.981
28.11


In [0]:
#mean texture 
mean_tx=np.mean(a[:,1])
print(mean_tx)
medi_tx=np.median(a[:,1])
print(medi_tx)
std_tx=np.std(a[:,1])
print(std_tx)
var_tx=np.var(a[:,1])
print(var_tx)
min_tx=np.min(a[:,1])
print(min_tx)
max_tx=np.max(a[:,1])
print(max_tx)

19.289648506151142
18.84
4.297254637090421
18.46639741599513
9.71
39.28


In [0]:
max_rm=np.max(a[:,0])
print(max_rm)

28.11


In [0]:
#mean perimeter
mean_pe=np.mean(a[:,2])
print(mean_pe)
medi_pe=np.median(a[:,2])
print(medi_pe)
std_pe=np.std(a[:,2])
print(std_pe)
var_pe=np.var(a[:,2])
print(var_pe)
min_pe=np.min(a[:,2])
print(min_rm)
max_rm=np.max(a[:,2])
print(max_rm)

91.96903339191564
86.24
24.27761929305318
589.4027985384281
6.981
188.5


In [0]:
## for문으로 반복부분 실행?
